# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test & Deploy

on:
  push:
    branches:
      - master
    tags-ignore:
      - v*
    paths:
      - src/**/*
      - public/**/*
      - playground/**/*

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - run: |
          yarn
          yarn test

      - name: Clone docs branch
        uses: actions/checkout@v3
        with:
          ref: docs
          path: temp

      - name: Build
        run: |
          yarn
          yarn build
          rsync -a dist/ temp

      - name: Commit and push
        run: |
          cd ./temp
          git add .
          git config user.email "x.li.gem@gmail.com"
          git config user.name "Github CI Bot"
          git commit -m "Site updated - `date '+%Y-%m-%d %H:%M:%S'`"
          git push
